
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://tolga-han.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl:

# Google tracking id to track your visitors

google-tracking-id: "UA-70768366-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Tolgahan Cakaloglu"
title: "{ Tolgahan Cakaloglu }"
description: "Blog and website of Tolgahan Cakaloglu, blogging mainly for Deep Learning, Artificial Intelligence, Machine Learning and Software Development"
keywords: "tolgahan, cakaloglu, tolgahan cakaloglu, deep learning, software architecture, software development, development, artificial intelligence, machine learning"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "<small>Talent wins games, but teamwork and intelligence wins championships. </br> <b><i> M.Jordan</i></b></small>"
  - text: "<small>If I had asked people what they wanted, they would have said faster horses. </br> <small><b><i> H.Ford</i></b></small>"
  - text: "<small>Being honest and plain may not let you have a lot of friends however it will always help you to get the right ones</small>"

me-img: "/img/jetpacktocat.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "jackalhan"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ualr.jpg"
    date: "Aug. 2014 - Today"
    description: "Arcitect of IT Department of EIT Building at University of Arkansas"
  - image: "/img/timeline/ualr.jpg"
    date: "Aug. 2014 - Today"
    description: "Started to pursue a Ph.D on Computer Science with roles of research and teaching assistant at University of Arkansas"
  - image: "/img/timeline/turkishAirlines.jpg"
    date: "Nov. 2012 - Oct. 2015"
    description: "Project Manager of Commercial Service SOA (Service Oriented Architecture) Solutions at Turkish Airlines"
  - image: "/img/timeline/turkishAirlines.jpg"
    date: "Oct. 2010 - Nov. 2012"
    description: "Development Team Leader of Miles&Smiles Loyalty and CRM Solutions at Turkish Airlines"
  - image: "/img/timeline/turkishAirlines.jpg"
    date: "Feb. 2008 - Oct. 2010"
    description: "Senior Programmer of Miles&Smiles Loyalty and CRM Solutions at Turkish Airlines"
  - image: "/img/timeline/baby.jpg"
    date: "March 2004 - Today"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "jackalhan@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/tolgahan.cakaloglu.9"
  - title: "twitter"
    url: "https://twitter.com/t_cakaloglu"
  - title: "github"
    url: "https://github.com/jackalhan"
  - title: "linkedin"
    url: "https://linkedin.com/in/tolgahan"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Bio: 'about'
  Timeline: 'timeline'
  Publications: 'publications'
  #Projects: 'projects'
  #Sundry: 'sundry'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
